### ISSUE TITLE
Handle base addresses

### ISSUE THREAD

**Issue by probins** [timreichen/importmap#1]
This seems to handle 'bare' specifiers and specifiers with trailing slash well, but AFAICS doesn't handle the example given in https://github.com/WICG/import-maps#general-url-like-specifier-remapping where the specifier to be mapped starts with `/`, i.e. applies to all relative addresses as well. In this case, `./helpers.mjs` or `../../../helpers.mjs` should all be mapped. In other words, relative addresses have to be resolved to the base address before comparing with the value in the import map.

In my case, I'm using this to use a different `deps.js` in certain circumstances. `/lib/deps.js` should match all relative addresses, regardless of where the importer is in the directory tree. For reference, this works in Chrome.

**Comment by timreichen** [comment]
Could that be achieved by setting the third argument (baseUrl) in `resolve`? Can you post example code for testing?

**Comment by probins** [comment]
I hadn't noticed there was a 3rd argument, but it works if you specify from the base address. I'm using it in a plugin which provides importee and importer. The importer is `file:///home/user/project/lib/...`, so if your base address is `/lib/...` you have to map without `file:///home/user/project`, i.e. `fromFileUrl` and without cwd.

So, to take my `/lib/deps.js` example, the import map maps `/lib/deps.js` to `/lib/anotherdeps.js`. Now assume you have `/lib/a.js` and `/lib/subdir/b.js`, which import from `./deps.js` and `../deps.js` respectively. If I set the 3rd argument to `/lib/a.js` and `/lib/subdir/b.js` respectively, then it works. But it doesn't work if I use `file:/// and so on`.

A simple case like that should be good enough for a test.

**Comment by probins** [comment]
PS If you want tests, Chromium's test suite is at https://chromium.googlesource.com/chromium/src/+/1d1222b38aeaef805af41683c3648623b710b7b2/third_party/blink/web_tests/external/wpt/import-maps/data-driven/resources Import maps have just been enabled by default; will be in Chrome 89.

**Comment by probins** [comment]
after using this module for a while, I find that it works well for all cases if I always supply the importer in the form of an absolute path. As I see it, the problem with this module is that the code assumes there is a baseUrl to resolve relative addresses against, but baseUrl is not used in the docs/examples. This means, as documented, it can't handle relative addresses.

So I would suggest making baseUrl required, and changing the docs/examples to match. I would also suggest, as a convenience for users, changing the code so it can also handle baseUrl in the form of a fully resolved url (i.e. convert it to baseUrl by removing the protocol and cwd).

**Comment by timreichen** [comment]
Sorry for my late response. I don't have much time at the moment but I will try to look into that. I also want to port the chromium tests to deno tests. PRs are welcome.

**Comment by timreichen** [comment]
@probins I added pwt tests and changed the functionality to be able to handle baseURLs.

**Comment by probins** [comment]
ok thanks. I'll let you know if I find any issues.
