### ISSUE TITLE
Use WPT tests

### ISSUE THREAD

**Issue by lucacasonato** [timreichen/importmap#2]
Thanks for the library @timreichen

To test conformance, this library should use the canonical web platform tests maintained by spec authors. See https://github.com/web-platform-tests/wpt/tree/master/import-maps/data-driven and how they are used in Deno CLI: https://github.com/denoland/deno/blob/main/cli/import_map.rs#L688

**Comment by timreichen** [comment]
👍 on it

**Comment by timreichen** [comment]
@lucacasonato I added the wpt tests json data taken from [here](https://chromium.googlesource.com/chromium/src/+/1d1222b38aeaef805af41683c3648623b710b7b2/third_party/blink/web_tests/external/wpt/import-maps/data-driven/resources).

**Comment by lucacasonato** [comment]
Awesome! Thanks for the effort :-)
