### ISSUE TITLE
Add `useActiveImportMap` option to `resolveModuleSpecifier`

### ISSUE THREAD

**Issue by ayoreis** [timreichen/importmap#3]
I already wrote the implementation for it since I need the feature: [ayoreis/importmap](https://github.com/ayoreis/importmap).

It uses `import.meta.resolve` which takes into account the current import map, and compares that to `serialiseURL(new URL(specifier, import.meta.url))`, if not equal (meaning using import map) it returns the `import.meta.resolve` resolved, if equal it returns the manually resolved one.

When `useActiveImportMap` is `true` It does not account for the user-specified `importMap` option, which could be implemented, but since neither Deno nor the browser has a way of specifying more than one import map I left it like this.

I also didn't write automatic tests yet (I did do by manually testing different locations and import maps).

Do you want to merge this? I also made other changes while working on this, you can merge those if you wish.

**Comment by ayoreis** [comment]
Just realized this won't work with import map scopes. Have to add a note about that.

**Comment by timreichen** [comment]
What is the use case of this exactly?

**Comment by ayoreis** [comment]
I made a ponyfill for dynamic imports to be used in Deno Deploy and `deno compiled`d modules (https://github.com/ayoreis/import). I use esbuild with esbuild_deno_loader (that uses this) to compile a module to an IIFE and run that (via `Function`), and I want it to resolve imports using the current import maps without the user needing to pass it as an argument. That is my use case, maybe other people may have others.

**Comment by timreichen** [comment]
Thanks for your suggestion. I would like to keep that repo as a bare spec implementaion without any runtime specific stuff.
