### ISSUE TITLE
proposal: support `deno.json` as import map

### ISSUE THREAD

**Issue by iuioiua** [timreichen/importmap#4]
I've implemented support for imports within `deno.json` in https://github.com/denoland/fresh/pull/1188. It works by feeding `denoPlugins()` from this module either the `deno.json` or import map location (URL). When feeding it the Deno configuration file URL, [`resolveImportMap()`](https://github.com/timreichen/importmap/blob/master/mod.ts#L200) prints:
```
an invalid top-level key was present in the import map.
Import map diagnostics:
  - Invalid top-level key "lock". Only "imports" and "scopes" can be present.
  - Invalid top-level key "tasks". Only "imports" and "scopes" can be present.
  - Invalid top-level key "compilerOptions". Only "imports" and "scopes" can be present.
```
In a way, I think `deno.json` is an import map, as it can contain the same `imports` property. I propose that either:
1. We remove these printed errors. Con: These errors may indeed be useful.
2. We add support for `deno.json` fields to accept them without error. Con: This will mean a little more maintenance in the future as the shape of `deno.json` evolves.

**Comment by iuioiua** [comment]
@timreichen, gently pinging. WDYT?

**Comment by timreichen** [comment]
I checked with the specs.

> 1. We remove these printed errors. Con: These errors may indeed be useful.

The errors are part of the spec, but the strictness could be loosened by replacing error throws with console warnings.
This approach would theoretically work, but it would always show warnings which is probably not desired.

> We add support for deno.json fields to accept them without error. Con: This will mean a little more maintenance in the future as the shape of deno.json evolves.

Since this is a pure spec implementation, I think it would be better to add a dedicated std/importmap mod with runtime specific adaptations instead of changing this mod. WDYT?

**Comment by iuioiua** [comment]
Fair points. Another possible solution is add an `ignoreErrors = false` or similar argument to the function. This would be non-breaking, maintain spec behaviour (by default) and offer the desired functionality. WDYT?

**Comment by iuioiua** [comment]
Actually, I may have a way around the need for any changes. I'll keep you updated.

**Comment by timreichen** [comment]
Or why not just extract `scopes` and `imports` and pass them instead of the whole object?

**Comment by iuioiua** [comment]
Yeah, I thought the same. Fresh uses [esbuild_deno_loader](https://deno.land/x/esbuild_deno_loader@0.7.0), so the change must be made there.

**Comment by timreichen** [comment]
Can this be closed?

**Comment by iuioiua** [comment]
Yep. I don't think the cause of my issue lies in this module. Thanks!
